name: Update Calendar

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4 icalendar pytz
          playwright install chromium
      
      - name: Run scraper
        env:
          EDC_USERNAME: ${{ secrets.EDC_USERNAME }}
          EDC_PASSWORD: ${{ secrets.EDC_PASSWORD }}
          EDC_HASH_URL: ${{ secrets.EDC_HASH_URL }}
          EDC_USER_ID: ${{ secrets.EDC_USER_ID }}
        run: python scraper.py
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
